### ISSUE TITLE
Allow skipping randomly-picked games

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#103]
In cases where a random game is unfavorable, players should be able to run `/game skip` to get a new game.

**Comment by Restioson** [comment]
Would this work on a voting basis? I.e, 50% or so need to vote to skip?

**Comment by haykam821** [comment]
For now this could be limited to operators only, but it would be useful to introduce voting for commands like these.

**Comment by Restioson** [comment]
As far as I know, /game stop in a circular channel will continue the channel but skip the game

**Comment by Gegy** [comment]
It doesn't currently- but this is legacy from when circular channels were games themselves. We can change /game stop to match the behavior as described for skip.
