### ISSUE TITLE
Split events into scoped events library

### ISSUE THREAD

**Issue by Gegy** [NucleoidMC/plasmid#104]
This will be useful for leukocyte, but also for many other cases where events are useful without having a Plasmid minigame running.

This could potentially include rules too which we might be able to couple more closely with the related events, since a common pattern is for a rule to match an event exactly. In this case, leukocyte would become just a wrapper around this library that supports setting these rules with persistence from a command interface.

**Comment by Restioson** [comment]
IMO, only the innermost (most nested in the scope) event handler should run. Otherwise, if they all ran, you would only be able to add new event handlers which cancel the event but not explicitly allow it, because cancellation always takes precedence over allowing.

**Comment by Gegy** [comment]
This is now resolved in 0.5 with the integration of [Stimuli](https://github.com/NucleoidMC/stimuli).
