### ISSUE TITLE
Statistics API

### ISSUE THREAD

**Issue by Gegy** [NucleoidMC/plasmid#105]
Plasmid should have an API for minigames to provide statistics for that given game. The use of this data can be up to external mods- in our case, nucleoid-extras, which will send these to the backend.

The API needs to be designed in such a way that each data point can indicate to the backend how it should be stored & displayed. For example, some may want to be stored as an average while others would be as a total.

**Comment by Geek202** [comment]
An idea for getting the statistics data out of plasmid and into other mods (nucleoid-extras) could be to add some Fabric API style events to plasmid for games being started/ending that provide access to data about the game such as the statistics. These events could also be used by other mods to show information when games are opened, for example to send statistics about a game to the client.

**Comment by Gegy** [comment]
Ah, yep! Events will definitely be needed to be exposed. :)

**Comment by Geek202** [comment]
I can take a look at seeing if I can implement a global events system that can be expanded as this gets implemented if you like. I'd assume the main ones would be game start/end, and potentially also some related to players joining/leaving games too.

**Comment by Gegy** [comment]
That would be wonderful! Thanks
