### ISSUE TITLE
Improve shop organization with the ShopBuilder

### ISSUE THREAD

**Issue by RedstoneParadox** [NucleoidMC/plasmid#106]
Currently, the shop builder doesn't have much in the way of methods for choosing how the shop is laid out. It would be nice if there was a way to tell the builder to start a new row of items, or to lay out the shop in columns instead of rows, to not have the items centered, etc.

**Comment by Gegy** [comment]
This is now better supported by the shop api since https://github.com/NucleoidMC/plasmid/commit/c6c24916a4e9ce0f9e8bee6ea43981efd868b19e.

However, this is not a complete solution: ideally we want to split out a full much more generic library for dealing with server-side uis.

**Comment by Gegy** [comment]
This is resolved in 0.5 with the integration of SGUI.
