### ISSUE TITLE
Menu channels act weird when joining existing game

### ISSUE THREAD

**Issue by ShockMicro** [NucleoidMC/plasmid#148]
If you try to join a game in progress which goes through a menu channel, it brings you to the menu, even though there's already a game going on in the channel.

**Comment by ShockMicro** [comment]
This happened with loop de loop, not sure about the other menu channels. I just did /game join, not specifying anything else.

**Comment by Gegy** [comment]
This is intentional, each option in the menu represents a different game instance.

**Comment by Gegy** [comment]
This is resolved in 0.5 where `/game join` now is processed through GameSpaces directly.
