### ISSUE TITLE
[Feature Request] Custom game opening messages

### ISSUE THREAD

**Issue by Draylar** [NucleoidMC/plasmid#17]
Using
![image](https://user-images.githubusercontent.com/17728338/90190308-62216a00-dd84-11ea-80ef-2291af27e8a4.png)
always prints the same message to chat:

![image](https://user-images.githubusercontent.com/17728338/90190331-6d749580-dd84-11ea-879f-20431c5bb3d9.png)

It would be nice if these were customizable. The messages currently come from `GameCommand`, which means the `GameType` would most likely have to handle this.

**Comment by CodersInABarrel** [comment]
i could try

**Comment by Gegy** [comment]
This is mostly handled now by the game open handle displaying the game name specified by the config JSON- is this still necessary?
