### ISSUE TITLE
AFK players should not delay game start

### ISSUE THREAD

**Issue by ashhhleyyy** [NucleoidMC/plasmid#234]
Currently plasmid waits until all players have joined a game before starting the short countdown, which can cause games to take an unnecessary amount of time to start when a single player is AFK and does not join.

**Comment by haykam821** [comment]
Which implementation makes the most sense to you?

- Integrate with the API of a mod such as [AfkDisplay](https://modrinth.com/mod/afkdisplay) directly
- Add AFK role support to Player Roles and use an assigned AFK role for detection
