### ISSUE TITLE
Wood type saplings should be renamed to plants

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#254]
While the first six wood types do have saplings, propagules stretch the definition of saplings, and fungi are not saplings.

To fix this issue, the references to saplings in the `WoodType` should be replaced with deprecation if necessary.

https://github.com/NucleoidMC/plasmid/blob/de5d3ef8587c65e0bd96ee8980e002feec68bf85/src/main/java/xyz/nucleoid/plasmid/util/WoodType.java#L67-L69

**Comment by ayrotideysarkar** [comment]
hi is this up for hacktoberfest?
@haykam821
