### ISSUE TITLE
Games and game portals do not have registry access when being parsed from a command

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#259]
Currently, commands such as `/game open {type: "colorswap:color_swap"}` parse the game configuration argument with `NbtOps`. However, this means that game configuration codecs that require registry access will not work. Game configurations are already parsed from data packs with registry access, meaning some game configurations will only be parseable from data packs.

An instance of `RegistryOps` can wrap `NbtOps` to fix this issue:

```java
RegistryOps.of(NbtOps.INSTANCE, context.getSource().getRegistryManager())
```

**Comment by Gegy** [comment]
Resolved in 0caa4a6bb003cf7337e6bf85867be635e36fffd3.
