### ISSUE TITLE
Add a game rule for player movement

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#26]
A game rule for player movement would be helpful for cases where movement should be controlled by the game only, such as before the countdown ends in King of the Hill.

**Comment by gegy1000** [comment]
Oh, we totally need the ability to change game rules at game runtime, too. Currently it's only really properly supported in the game initializer.

**Comment by Restioson** [comment]
KOTH, Loop-de-loop, and the starter all have implementations of this, so maybe it would be good for plasmid to have it.

**Comment by gegy1000** [comment]
Closed in favour of tracking through #41
