### ISSUE TITLE
Add a listener for a player being hit by a projectile

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#27]
A listener for players being hit by a projectile would be helpful for games such as Snowball Fight, which would use the listener to eliminate players, or One in the Quiver, which would use it for scoring.

The listener should provide the projectile entity and the entity hit result as context. In addition, it should be cancellable to allow functionality that replaces the vanilla behavior.

**Comment by SuperCoder7979** [comment]
Added in 0.3 :D
