### ISSUE TITLE
The bundled version of MixinExtras from Fabric loader should be used

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#285]
[Fabric loader 0.15.0](https://github.com/FabricMC/fabric-loader/releases/tag/0.15.0) includes MixinExtras, so when updating the loader version, the separate dependency and repository declarations for MixinExtras can be removed.

https://github.com/NucleoidMC/plasmid/blob/31a71aa8e26632c77cbdd17a0100ba694a65f1b9/build.gradle#L111

**Comment by Gegy** [comment]
Done in https://github.com/NucleoidMC/plasmid/commit/251995f385ab0fe297c090897fb987cc1a0a667d
