### ISSUE TITLE
/game test <id> command ?

### ISSUE THREAD

**Issue by Restioson** [NucleoidMC/plasmid#62]
This command would open and then immediately start a game, making it just a little easier to test games locally

**Comment by Restioson** [comment]
From #78: maybe it could close current game also

**Comment by redcreeper14385** [comment]
It could also disable any time limits.

**Comment by Restioson** [comment]
> It could also disable any time limits.

This would be an anti-feature if you wanted to test the time limit. Futhermore, the time limit is not handled by plasmid, but by the minigame.

**Comment by redcreeper14385** [comment]
That's a good point, perhaps you should be able to change the game configuration on the fly when in test mode? If this is even possible.

**Comment by haykam821** [comment]
That should be available anywhere a regular game identifier is usable for opening a game, and in the future we can utilize codec GUIs in order to maybe even allow regular players to customize games.

**Comment by haykam821** [comment]
As of bb67d341203a7e27acb40e129ae620f791cdd763, you can open a game with a NBT game config. This could be replicated in the `/game test` command as well.
