### ISSUE TITLE
Game config names should come from translations rather than a config property

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#64]
Rather than specifying the name of a game config inside the game config, it should be specified using translations. The current standard for translation keys is `game.<namespace>.<path>` and `gameType.<namespace>.<path>`. If no game config or game type translation is specified, the ID fallback should be used instead.

**Comment by Restioson** [comment]
Wouldn't this mean that different configs couldn't have different names?

**Comment by haykam821** [comment]
They could if they each have their own `game.<namespace>.<path>` translation, but otherwise they will fall back to a shared `gameType.<namespace>.<path>` translation.
