### ISSUE TITLE
Add a game rule for moving items in the inventory

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#8]
Currently, there is a game rule for managing whether players can throw items from their inventory on the ground.

https://github.com/NucleoidMC/plasmid/blob/e98560e50cb0eef5cb7f0a7cd01cb6de912ebf48/src/main/java/xyz/nucleoid/plasmid/game/rule/GameRule.java#L12

However, this does not prevent items from moving within the inventory. This would be helpful for games where a specific functionality is locked to a certain slot.

**Comment by Restioson** [comment]
Adding the bug label because this is closely related to another issue - `THROW_ITEMS` doesn't prevent you from opening your inventory and dragging the item out, which leads to it being thrown on the ground.

**Comment by gegy1000** [comment]
Closed in favour of tracking through #41
