### ISSUE TITLE
Certain listeners do not have documentation

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#85]
The following listeners do not have documentation:

- [`GameCloseListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/GameCloseListener.java)
- [`GameOpenListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/GameOpenListener.java)
- [`GameTickListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/GameTickListener.java)
- [`HandSwingListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/HandSwingListener.java)
- [`OfferPlayerListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/OfferPlayerListener.java)
- [`PlayerAddListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/PlayerAddListener.java)
- [`PlayerDamageListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/PlayerDamageListener.java)
- [`PlayerRemoveListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/PlayerRemoveListener.java)
- [`RequestStartListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/RequestStartListener.java)
- [`UseBlockListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/UseBlockListener.java)
- [`UseItemListener`](https://github.com/NucleoidMC/plasmid/blob/1.16/src/main/java/xyz/nucleoid/plasmid/game/event/UseItemListener.java)

**Comment by Gegy** [comment]
This is now resolved in 0.5 with the integration of [Stimuli](https://github.com/NucleoidMC/stimuli).
