### ISSUE TITLE
The Discord webhook error reporter allows passthrough of mentions

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/plasmid#92]
This can be fixed by adding the `allowed_mentions` field set to `{ parse: [] }` around here:

https://github.com/NucleoidMC/plasmid/blob/c834c80a9a2777d9953cdd7c2a9c3a44e0c353c5/src/main/java/xyz/nucleoid/plasmid/error/DiscordWebhook.java#L71-L74

**Comment by Gegy** [comment]
Closed in https://github.com/NucleoidMC/plasmid/commit/ba7b07e5c6892b8d49ee5592a280cf7fe11d0648
