### ISSUE TITLE
Rename listeners in a consistent fashion

### ISSUE THREAD

**Issue by Restioson** [NucleoidMC/plasmid#97]
Currently the names of listeners are somewhat arbitrary, e.g why is it `UseItemListener` and not `PlayerUseItemListener` to follow the convention set by `PlayerPunchBlockListener`? Either way, one of these needs to be renamed to fit with the other. This is not the only such instance of naming inconsistency and it harms listener discoverability.

**Comment by Gegy** [comment]
This is now resolved in 0.5 with the integration of [Stimuli](https://github.com/NucleoidMC/stimuli).
